# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

num_clip_cpp <- function(x, a, b) {
    .Call('OpenSDP_data_num_clip_cpp', PACKAGE = 'OpenSDP.data', x, a, b)
}

